const strains = [
  "Topo Twist Molten Sticky Mist",
  "Sticky Mist",
  "Topo Chico Golden Smooth Milk",
  "Purple Frosty Pop",
  "Cherry Wave",
  "Wild Electric Jam",
  "Midnight Velvet Fog",
  "Platinum Thunder",
  "Crispy Cosmic Diesel",
  "Street Anthem Dank Thunder",
  "Frozen Kush",
  "Wavy Sticky Haze",
  "Crimson Electric Berry",
  "Lemon Whip",
  "Frosty Golden Thunder",
  "Sole Fire Midnight Wavy Cookies",
  "Neon Diesel",
  "Mic Check Frosty Electric Buzz",
  "Lemon Cookies",
  "Crispy Cake",
  "Platinum Cosmic Fuel",
  "Cloudy Snap",
  "Wavy Hazey Mist",
  "Platinum OG",
  "Tennessee Turbo Dank Buzz",
  "Neon Whip",
  "Velvet Glue",
  "Topo Twist Cloudy Jam",
  "Velvet Atomic Cake",
  "Stepback OG Sticky Roll",
  "Funky Neon Cake",
  "Cherry Slap",
  "Blazing Lunar Snap",
  "Cosmic Kush",
  "Sticky Fuel",
  "Blazing Cake",
  "Neon Purple Crush",
  "Jordan OG Sticky Mist",
  "Frosty Cosmic Cookies",
  "Sneaker Drop Smooth Midnight Milk",
  "Honky Tonk Atomic Dank Glue",
  "Cloudy Berry",
  "Cloudy Runtz",
  "Topo Twist Sticky Hazey Drop",
  "Crispy Berry",
  "Purple Atomic Fuel",
  "Court Blaze Smooth Frosty Kush",
  "Blazing Atomic Thunder",
  "Frosty Blast",
  "Cosmic Ghost Mist",
  "Cosmic Storm",
  "Neon Hazey Kush",
  "Frosty Frozen Snap",
  "Wild Spicy Runtz",
  "Frozen Turbo Cake",
  "Smooth Purple Muffin",
  "Golden Fog",
  "Hazey Velvet Punch",
  "Crimson Haze",
  "Lunar Fog",
  "Chat Ripper Purple Fuel",
  "Wavy Cherry Storm",
  "Turbo Neon Whip",
  "Dreamy Crimson Crush",
  "Ghost Ghost Berry",
  "Ball Up Crimson Roll",
  "Funky Roll",
  "Crimson Cookies",
  "Sticky Purple Diesel",
  "Golden OG",
  "Smooth Punch",
  "Frozen Pop",
  "Cloudy Molten Kush",
  "Hazey Muffin",
  "Midnight Slap",
  "Turbo Hazey Berry",
  "Nashville Crispy Cake",
  "Electric Cake",
  "Turbo Thunder",
  "Golden Dreamy Jam",
  "Platinum Dreamy Thunder",
  "Lemon OG",
  "Wild Frozen Runtz",
  "Crispy Buzz",
  "Golden Mist",
  "Molten Slap",
  "Wavy Drizzle",
  "Funky Ghost Fuel",
  "Cosmic Atomic Cake",
  "Molten Golden Cake",
  "Atomic Kush",
  "Sneaker Drop Frozen Cloudy Cookies",
  "Atomic Haze",
  "Dank Berry",
  "Frosty Fuel",
  "Topo Dream Molten Pop",
  "Cosmic Drizzle",
  "Cloudy Fog",
  "Smooth Fog",
  "Smooth Berry",
  "Atomic Jam",
  "Boom Bap Atomic Slap",
  "Funky Cake",
  "Spicy Electric Slap",
  "Cherry Lunar Thunder",
  "Platinum Storm",
  "Electric Berry",
  "45 RPM Golden Spicy Cookies",
  "Golden Runtz",
  "Platinum Drop",
  "Cherry Crush",
  "Crate Digger Blazing Cherry Drizzle",
  "Golden Neon Cake",
  "Crimson Purple Jam",
  "Midnight Cloudy Crush",
  "Electric Buzz",
  "Boom Bap Neon Jam",
  "Boom Bap Molten Dank Storm",
  "Boom Bap Ghost Atomic Diesel",
  "Purple Blast",
  "Boom Bap Midnight Snap",
  "Cloudy Storm",
  "Molten Crush",
  "Cosmic Golden Haze",
  "Crispy Punch",
  "Stepback OG Blazing Kush",
  "Lemon Platinum Glue",
  "Crimson Fog",
  "Sticky Spicy Milk",
  "Platinum Wave",
  "Spicy Milk",
  "Golden Drizzle",
  "Turbo Frosty Fog",
  "Spicy Haze",
  "Ball Up Turbo Drop",
  "Frozen Lunar Jam",
  "Frosty Diesel",
  "Dreamy Cake",
  "Neon Wavy Roll",
  "Smooth Golden Crush",
  "Court Blaze Wild Golden Milk",
  "Blazing Kush",
  "Crispy Atomic Diesel",
  "Purple Crush",
  "Purple Cake",
  "Molten Midnight Buzz",
  "Crimson Blast",
  "Golden Glue",
  "Fastbreak Dream Frosty Crimson Haze",
  "Lunar Atomic Mist",
  "Golden Dank Mist",
  "Cloudy Buzz",
  "Sticky Jam",
  "Smooth Glue",
  "808 Midnight Storm",
  "Electric Funky Slap",
  "45 RPM Frozen Berry",
  "Frosty Runtz",
  "Frosty Cloudy Muffin",
  "Dank Diesel",
  "Purple Fuel",
  "Sticky Cake",
  "Dank Midnight Cookies",
  "Crate Digger Molten Dreamy Muffin",
  "Lemon Crush",
  "Ball Up Hazey Crush",
  "Dank Dreamy OG",
  "Lemon Frozen Muffin",
  "Dank Buzz",
  "Smooth Funky Buzz",
  "Molten Turbo Storm",
  "Atomic OG",
  "Crimson Cosmic Buzz",
  "Velvet Velvet Thunder",
  "Hazey Turbo Drizzle",
  "Funky Fuel",
  "Crispy Crispy Kush",
  "Blazing Electric OG",
  "Tennessee Wild Haze",
  "Boom Bap Smooth Electric Roll",
  "Dank Snap",
  "Platinum Jam",
  "Wild Berry",
  "Cosmic Wild Diesel",
  "Dreamy Velvet Fog",
  "Tennessee Crispy Wave",
  "Smooth Lunar Jam",
  "Ghost Ghost Crush",
  "Dank Wavy Muffin",
  "Graffiti OG Cosmic Turbo OG",
  "Honky Tonk Cherry Cake",
  "Crimson Drizzle",
  "Wavy Berry",
  "Ghost Purple Fog",
  "Cherry Spicy Jam",
  "Funky Berry",
  "Cloudy Drop",
  "Topo Twist Velvet Lemon Whip",
  "Atomic Dreamy Diesel",
  "Turbo Cookies",
  "Velvet Cloudy Runtz",
  "Sticky Punch",
  "Frozen Glue",
  "Golden Golden Thunder",
  "Neon Cloudy Whip",
  "Dank Dreamy Cake",
  "Lunar Berry",
  "Golden Crimson Runtz",
  "Jordan OG Platinum Wave",
  "Cosmic Berry",
  "Lemon Wild Glue",
  "Atomic Smooth Blast",
  "Crimson Diesel",
  "Rate's Wonder Dank",
  "Honky Tonk Spicy Snap",
  "Velvet Wave",
  "Platinum Purple Kush",
  "Funky Thunder",
  "Flaco's OG Purp",
  "Ghost Crispy Berry",
  "Sticky Roll",
  "Lunar Hazey Drop",
  "Sticky Cloudy Buzz",
  "Midnight Smooth Drizzle",
  "Electric Sticky Wave",
  "Purple Drop",
  "Volunteer Frosty Mist",
  "Atomic Whip",
  "Ghost Haze",
  "Volunteer Lunar Hazey Slap",
  "Molten Mist",
  "Blazing Molten Punch",
  "Needle Drop Midnight Neon Storm",
  "Purple Wild Haze",
  "Fader Frozen Platinum Whip",
  "Groove Dust Spicy Muffin",
  "Sneaker Drop Spicy Blazing Haze",
  "Fader Turbo Haze",
  "Neon Frosty Fog",
  "Spicy Frozen Punch",
  "Golden Wild Cake",
  "Sticky Hazey Diesel",
  "Sticky Pop",
  "Cynsaytional's OG Eric",
  "Crimson Turbo Haze",
  "Hazey OG",
  "Frosty Midnight Glue",
  "Frosty Crispy Crush",
  "Frozen Crimson OG",
  "Funky Milk",
  "Turbo Sticky Muffin",
  "Lemon Wild Fog",
  "Lunar Lunar Mist",
  "Spicy Wavy Whip",
  "Wavy Thunder",
  "Wavy Haze",
  "Chico Mist Smooth Sticky Muffin",
  "Golden Sticky Runtz",
  "Velvet Cloudy Jam",
  "Wavy Funky Jam",
  "Atomic Storm",
  "Platinum Molten Milk",
  "Hazey Milk",
  "Sneaker Drop Lemon Jam",
  "Wavy Electric Mist",
  "Platinum Drizzle",
  "Crimson Atomic Punch",
  "Funky Muffin",
  "Vinyl Spicy Blast",
  "Ghost Dreamy Kush",
  "Stepback OG Ghost Crush",
  "Frozen Crush",
  "Smooth Cake",
  "Topo Chico Atomic Platinum Buzz",
  "Lemon Fog",
  "Neon Jam",
  "Cherry Cherry Kush",
  "Needle Drop Platinum Electric Mist",
  "Fader Wild Storm",
  "Hazey Jam",
  "Midnight Cosmic Drop",
  "Frosty Buzz",
  "Sticky Wavy Slap",
  "Tennessee Purple Wild Runtz",
  "Wild Thunder",
  "Golden Milk",
  "Golden Molten Storm",
  "Fastbreak Dream Wild Crispy Cake",
  "Dank Spicy Berry",
  "Boom Bap Sticky Cherry Mist",
  "Frosty Lemon Punch",
  "Turbo Ghost Storm",
  "Wild Lunar Whip",
  "Frosty Roll",
  "Spicy Buzz",
  "Ghost Lemon Buzz",
  "Mixtape Crimson Purple Roll",
  "Smooth Spicy Jam",
  "Spicy Cloudy Crush",
  "Electric Whip",
  "Sole Fire Wavy Crimson Berry",
  "Frosty Jam",
  "Purple Mist",
  "Freestyle Funk Crimson Golden Pop",
  "Frosty Frosty OG",
  "Frozen Blast",
  "Electric Neon Jam",
  "Neon Midnight Buzz",
  "Funky Lunar OG",
  "Atomic Muffin",
  "Dank Punch",
  "Hazey Lemon Whip",
  "Ghost Cloudy Wave",
  "Velvet Punch",
  "Blazing Cosmic Buzz",
  "Frosty Blazing Buzz",
  "Spicy Dank Snap",
  "Dreamy Dank Storm",
  "Velvet Atomic Berry",
  "Crimson Cloudy Fog",
  "Dreamy Storm",
  "Funky Drop",
  "Dreamy Velvet Jam",
  "Lunar Neon Buzz",
  "Velvet Golden Cookies",
  "Turbo Berry",
  "Mic Check Wild OG",
  "Dank Blazing Berry",
  "Golden Frozen Fog",
  "Blazing Wave",
  "Electric Crispy Wave",
  "Sticky Wavy Mist",
  "Honky Tonk Smooth Snap",
  "Platinum Molten Wave",
  "Cloudy Cloudy Wave",
  "Midnight Spicy Buzz",
  "Frozen Fuel",
  "Frosty Cosmic Muffin",
  "Lemon Blazing Buzz",
  "Topo Chico Midnight Kush",
  "Molten Wild Thunder",
  "Spicy Jam",
  "Electric Frosty Jam",
  "Velvet Thunder",
  "Bassline Ghost Golden Kush",
  "Crispy Wild Blast",
  "Platinum Cherry Roll",
  "Crispy Crimson Fuel",
  "Purple Wavy Kush",
  "Cosmic Electric Fog",
  "Platinum Buzz",
  "Neon Lemon Muffin",
  "Wavy Crispy Jam",
  "Deadstock Wavy Mist",
  "Frozen Atomic Fuel",
  "Dank OG",
  "Wavy Kush",
  "Wild Blast",
  "Sneaker Drop Turbo Muffin",
  "Velvet Spicy Blast",
  "Neon Dreamy Kush",
  "Neon Ghost Kush",
  "Wild Mist",
  "Cherry Ghost Berry",
  "Volunteer Cloudy Pop",
  "Freestyle Funk Purple Thunder",
  "Cloudy Neon Jam",
  "Cherry Hazey Pop",
  "Dreamy Fog",
  "Neon Cloudy OG",
  "Cherry Purple Milk",
  "Sticky Crimson Drizzle",
  "Golden Blazing Slap",
  "Golden Velvet Drizzle",
  "Lemon Crimson Jam",
  "Dank Spicy Pop",
  "Turbo Crimson Buzz",
  "Smooth Wavy Pop",
  "Mineral Buzz Blazing Blast",
  "Neon Buzz",
  "Hazey Cherry Storm",
  "Lunar Crimson Thunder",
  "Purple Wavy Cookies",
  "Cloudy Electric Mist",
  "Molten Storm",
  "Nashville Smooth Buzz",
  "Funky Frozen Muffin",
  "Platinum Milk",
  "Turbo Cherry Runtz",
  "Electric Punch",
  "Funky Diesel",
  "Funky Punch",
  "Fastbreak Dream Frosty Funky Diesel",
  "Velvet Velvet Fog",
  "Cosmic Drop",
  "Hazey Wavy Jam",
  "Cherry Storm",
  "Cloudy Purple Drop",
  "Dreamy Punch",
  "Atomic Fuel",
  "Purple Haze",
  "Purple Diesel",
  "Turbo Lemon OG",
  "Funky Wavy Fuel",
  "Crimson Berry",
  "Lemon Haze",
  "Cosmic Wave",
  "Crispy Wavy Pop",
  "Dank Sticky OG",
  "Sticky Frosty Runtz",
  "Atomic Diesel",
  "Turbo Buzz",
  "Blazing Fog",
  "Turbo Atomic Snap",
  "Blazing Neon Cookies",
  "Smooth Muffin",
  "Cosmic Glue",
  "Spicy Whip",
  "Neon Haze",
  "Clip Storm Dank Golden Pop",
  "Dank Hazey Kush",
  "Blazing Storm",
  "Cherry Berry",
  "Spicy Punch",
  "Cherry Sticky Runtz",
  "Platinum Pop",
  "Wavy Blazing Snap",
  "Dreamy Muffin",
  "Spicy OG",
  "Frosty Atomic Fuel",
  "Molten Punch",
  "Dreamy Snap",
  "Frozen Slap",
  "Blazing Milk",
  "Spicy Dreamy Slap",
  "Neon Blazing Milk",
  "Bassline Midnight Haze",
  "Midnight Roll",
  "45 RPM Velvet Cookies",
  "Topo Twist Frosty Dreamy Runtz",
  "Platinum Neon Storm",
  "Ghost Neon Crush",
  "Atomic Ghost Jam",
  "Court Blaze Ghost Wild Berry",
  "Electric Midnight Milk",
  "Turbo Turbo Roll",
  "Lemon Ghost Drop",
  "Freestyle Funk Purple Platinum Buzz",
  "Crimson Glue",
  "Sticky Kush",
  "Blazing Frosty Jam",
  "Smooth Golden Thunder",
  "Turbo Wild Fog",
  "Molten Velvet Thunder",
  "Fastbreak Dream Frozen Midnight Berry",
  "Midnight Crush",
  "Dreamy Blast",
  "Mineral Buzz Golden Platinum Snap",
  "Midnight Glue",
  "Purple Crimson Thunder",
  "Purple Jam",
  "Frozen Jam",
  "Graffiti OG Blazing Neon Cookies",
  "Crispy Jam",
  "Molten Frozen Wave",
  "Crimson Smooth Fuel",
  "Wavy Jam",
  "Crispy Wavy Slap",
  "Clip Storm Cloudy Cake",
  "Mic Check Midnight Crush",
  "Volunteer Midnight Kush",
  "Lunar Fuel",
  "Turntable Electric Buzz",
  "Mixtape Crimson Sticky Runtz",
  "Velvet Runtz",
  "Electric Blast",
  "Ghost Cosmic Glue",
  "Lemon Roll",
  "Ghost Golden Pop",
  "Spicy Funky Fog",
  "Midnight Midnight Punch",
  "Sticky Dreamy Storm",
  "Platinum Fog",
  "Wild Cherry Jam",
  "Blazing Drizzle",
  "Dreamy Hazey Diesel",
  "Lemon Hazey Punch",
  "Topo Chico Frosty Velvet Fuel",
  "Sole Fire Neon Frosty Crush",
  "Spicy Blazing Blast",
  "Turbo Muffin",
  "Spicy Blazing Drop",
  "Funky Drizzle",
  "Molten Runtz",
  "Blazing Crimson Runtz",
  "Purple Ghost Glue",
  "Hazey Wavy Drizzle",
  "Dreamy Frozen Thunder",
  "Hazey Turbo Milk",
  "Ghost Punch",
  "Frozen Lemon Mist",
  "Purple Sticky Kush",
  "Lemon Muffin",
  "Livewire Wild Roll",
  "Crispy Smooth Wave",
  "Blazing Frosty Storm",
  "Freestyle Funk Cloudy Midnight Jam",
  "Platinum Blast",
  "Jordan OG Frozen Frozen Whip",
  "Dank Frosty Buzz",
  "Cloudy Whip",
  "Smooth Storm",
  "Streamer Velvet Platinum Storm",
  "Golden Frozen Fuel",
  "Platinum Turbo Cookies",
  "Lunar Spicy Fog",
  "Frozen Whip",
  "Mineral Buzz Crispy Milk",
  "Platinum Funky Berry",
  "Golden Midnight Glue",
  "Wavy Ghost Crush",
  "Smooth Blazing Glue",
  "Crispy Milk",
  "Neon Electric Kush",
  "Sticky Dank Mist",
  "Wild Glue",
  "Frosty Drop",
  "Neon Glue",
  "Platinum Kush",
  "Blazing Crimson Blast",
  "Cloudy Haze",
  "Lunar Crush",
  "Platinum Molten Jam",
  "Lemon Funky Cookies",
  "Molten Muffin",
  "Neon Cookies",
  "Smooth Drizzle",
  "Spicy Spicy Slap",
  "Purple Lunar Jam",
  "Wax Drip Cloudy Frozen Muffin",
  "Cloudy Mist",
  "Court Blaze Neon Snap",
  "Lemon Smooth Drizzle",
  "Mixtape Lemon Berry",
  "Mixtape Blazing Crimson Runtz",
  "Midnight Neon Muffin",
  "Wavy Molten Milk",
  "Ghost Thunder",
  "Crimson Runtz",
  "Sticky Smooth Jam",
  "Fastbreak Dream Lemon Cake",
  "Funky Pop",
  "Ghost Milk",
  "Tennessee Funky Crispy Wave",
  "Cipher Crispy Dreamy Muffin",
  "Purple OG",
  "Cosmic Thunder",
  "Sole Fire Spicy Buzz",
  "Sticky Fog",
  "Dreamy Glue",
  "Lunar Blast",
  "Dank Sticky Thunder",
  "Neon Ghost Drop",
  "Midnight Turbo Mist",
  "Cloudy Diesel",
  "Ball Up Wavy Frozen Runtz",
  "Purple Slap",
  "Velvet Neon Diesel",
  "Midnight Drizzle",
  "Crispy Blazing Whip",
  "Purple Smooth Glue",
  "Dreamy Lunar Thunder",
  "Cloudy Spicy Snap",
  "Atomic Velvet Fuel",
  "Velvet Turbo Thunder",
  "Record Flip Purple Mist",
  "Crispy Crush",
  "Frosty Milk",
  "Wavy Funky OG",
  "Smooth Crush",
  "Crimson Molten Fuel",
  "Crispy Wavy Cake",
  "Blazing OG",
  "Smoky Mountain Velvet Milk",
  "Ghost Cookies",
  "45 RPM Golden Golden Glue",
  "Dank Blazing Drizzle",
  "Stepback OG Frozen Frosty Crush",
  "Purple Funky Jam",
  "Spicy Kush",
  "Jordan OG Blazing Buzz",
  "Cosmic Ghost Glue",
  "Purple Runtz",
  "Mineral Buzz Electric Midnight Slap",
  "Turbo Pop",
  "Clip Storm Crispy Cake",
  "Electric Fuel",
  "Wild Cookies",
  "Mixtape Platinum Dreamy Muffin",
  "Funky Glue",
  "High Top Haze Dank Drizzle",
  "Lunar Electric Storm",
  "Wild Midnight Snap",
  "Wild Jam",
  "Crispy Haze",
  "Molten Funky OG",
  "Lemon Pop",
  "Wavy Dank Diesel",
  "Turntable Lunar Wave",
  "Lemon Purple Diesel",
  "Cosmic Platinum Whip",
  "Streamer Cosmic Midnight Cookies",
  "Dreamy Frosty Wave",
  "Smooth Midnight Berry",
  "Smooth Smooth Thunder",
  "Molten Crispy Milk",
  "Platinum Frosty Buzz",
  "Electric Glue",
  "Cherry Crispy Snap",
  "Crispy Velvet Berry",
  "Crispy OG",
  "Platinum Turbo Punch",
  "Cosmic Cosmic Buzz",
  "Cherry Blazing Kush",
  "Lemon Buzz",
  "Spicy Platinum Jam",
  "Sticky Muffin",
  "Topo Twist Turbo Diesel",
  "Velvet Diesel",
  "Spicy Dreamy Pop",
  "Molten Dreamy Mist",
  "Sticky Platinum Mist",
  "Frosty Mist",
  "Blazing Wavy Buzz",
  "Lemon Fuel",
  "Wavy Crimson Storm",
  "Cherry Smooth Mist",
  "Dreamy Diesel",
  "Crimson Lemon Snap",
  "Spicy Drizzle",
  "Funky Hazey Jam",
  "Cosmic Crimson Cake",
  "Freestyle Funk Velvet Lunar Jam",
  "Cosmic Midnight Drizzle",
  "Twitch Haze Smooth Cosmic Diesel",
  "Golden Sticky Haze",
  "Jordan OG Lunar Hazey Muffin",
  "Dreamy Drop",
  "Streamer Midnight Cloudy Mist",
  "Platinum Lunar Muffin",
  "Midnight Cherry Muffin",
  "Crimson Wave",
  "Turbo Punch",
  "Vinyl Melt Cloudy Blazing Drop",
  "Lunar Midnight Milk",
  "Cosmic Crispy Roll",
  "Ghost Frozen Mist",
  "Wavy Electric Wave",
  "Sticky Milk",
  "Turbo Dank Thunder",
  "Frosty Midnight Jam",
  "Wavy Frozen Berry",
  "Funky Purple Pop",
  "Molten Cosmic Pop",
  "Crispy Muffin",
  "Golden Midnight Wave",
  "Dank Roll",
  "Lunar Blazing Slap",
  "Topo Twist Ghost Atomic Drizzle",
  "Crispy Platinum Muffin",
  "Blazing Glue",
  "Freestyle Funk Neon Jam",
  "Electric Roll",
  "Fastbreak Dream Turbo Wild Kush",
  "Lunar Hazey Cake",
  "Cloudy Smooth Berry",
  "Atomic Sticky Mist",
  "Atomic Turbo OG",
  "Cloudy Wavy Blast",
  "Purple Thunder",
  "Lemon Cloudy Pop",
  "Funky Dreamy Whip",
  "Hazey Runtz",
  "Stepback OG Wavy Electric Berry",
  "Platinum Dreamy Haze",
  "Cherry Dreamy Haze",
  "Purple Muffin",
  "Cloudy Frozen Whip",
  "Crimson Mist",
  "Turbo Glue",
  "Lunar Whip",
  "Lunar Runtz",
  "Cherry Cake",
  "Frosty Hazey Drop",
  "Golden Berry",
  "Platinum Haze",
  "Midnight Frosty Cookies",
  "Wavy Fuel",
  "Spicy Muffin",
  "Tennessee Spicy Fog",
  "Wavy Wave",
  "Midnight Electric Drizzle",
  "Record Flip Neon Platinum Whip",
  "Boom Bap Funky Frosty Blast",
  "Ghost Whip",
  "Spicy Berry",
  "Smoky Mountain Crispy Cosmic Fog",
  "Crispy Blast",
  "Dank Cosmic Snap",
  "Funky Whip",
  "Mic Check Dank Glue",
  "Neon Blazing Roll",
  "Sticky Ghost Drop",
  "Rewind Purple Velvet Storm",
  "Platinum Wild Snap",
  "Crimson Cake",
  "Topo Twist Crispy Kush",
  "Funky Midnight Cookies",
  "Fastbreak Dream Cherry Turbo Berry",
  "Blazing Sticky Blast",
  "Wild Crush",
  "Platinum Purple Storm",
  "Blazing Muffin",
  "Jordan OG Turbo Pop",
  "Crate Digger Lunar Hazey Slap",
  "Turbo Neon Crush",
  "Spicy Glue",
  "Atomic Cloudy Milk",
  "Sticky Blazing Wave",
  "Purple Purple Snap",
  "Midnight Buzz",
  "Graffiti OG Sticky Punch",
  "Frosty Wild Crush",
  "Street Anthem Wild Milk",
  "Lunar Golden Jam",
  "Turbo OG",
  "Golden Muffin",
  "Crimson Cherry OG",
  "Mixtape Frosty Diesel",
  "Midnight Whip",
  "Molten Diesel",
  "Dank Dank Fuel",
  "Sticky Ghost Fuel",
  "Cherry Jam",
  "Platinum Molten Muffin",
  "Funky Crush",
  "Frosty Dank Fuel",
  "Memphis Golden Cookies",
  "Crispy Wild Drizzle",
  "Golden Molten Whip",
  "Tennessee Hazey Lemon Crush",
  "Golden Roll",
  "Cloudy Velvet Roll",
  "Crispy Neon Muffin",
  "Cherry Lemon Drop",
  "Wild Ghost Jam",
  "Groove Dust Cosmic Lemon Haze",
  "Cherry Fuel",
  "Blazing Lunar Drizzle",
  "Sticky Thunder",
  "Lunar Purple Diesel",
  "Hazey Cherry Milk",
  "Dreamy Electric OG",
  "Lemon Punch",
  "Crispy Cloudy Cake",
  "Electric Midnight Thunder",
  "Hazey Neon Haze",
  "Sticky OG",
  "Sneaker Drop Cherry Golden Kush",
  "Frosty Haze",
  "Spicy Cherry Punch",
  "Golden Snap",
  "Wild Kush",
  "808 Spicy Frosty Berry",
  "Graffiti OG Turbo Dreamy Whip",
  "Turbo Runtz",
  "Streamer Molten Electric Storm",
  "Dreamy Thunder",
  "Velvet Wavy Fuel",
  "Tennessee Dreamy Funky Whip",
  "Velvet Whip",
  "Platinum Funky Cake",
  "Molten Drop",
  "Platinum Lemon Haze",
  "Ghost Sticky Runtz",
  "Velvet Frosty Fuel",
  "Sticky Crispy Whip",
  "Molten Frozen Roll",
  "Stepback OG Hazey Roll",
  "Fastbreak Dream Funky Platinum OG",
  "Mineral Buzz Cherry Kush",
  "Blazing Sticky Diesel",
  "Turntable Cherry Jam",
  "Cherry Funky Storm",
  "Crimson Kush",
  "Spicy Ghost Wave",
  "High Top Haze Spicy Berry",
  "Neon Wave",
  "Wild OG",
  "Midnight Pop",
  "Ghost Runtz",
  "Funky Spicy Roll",
  "Wild Wavy Cookies",
  "Golden Cookies",
  "Atomic Purple Wave",
  "Frosty Thunder",
  "Lemon Neon Runtz",
  "Crimson Spicy Thunder",
  "Atomic Blast",
  "Neon Ghost Slap",
  "Dreamy Jam",
  "Frozen Muffin",
  "Sticky Golden Jam",
  "Wild Cake",
  "Fader Midnight Atomic Crush",
  "Neon Berry",
  "Delta Blues Cherry Jam",
  "Cosmic Ghost Wave",
  "Bubbly Lime Crimson Cherry Jam",
  "Atomic Frosty Kush",
  "Wavy Milk",
  "Velvet Wavy Drop",
  "Purple Lemon OG",
  "Crimson Buzz",
  "Blazing Crush",
  "Ghost Spicy Glue",
  "Lemon Cosmic Whip",
  "Midnight OG",
  "Turbo Midnight Jam",
  "Wavy Smooth Roll",
  "Bitrate Buzz Cherry Crispy Diesel",
  "Frozen Hazey Cookies",
  "Wavy Cloudy Drop",
  "Velvet Spicy Drop",
  "Crate Digger Neon Cake",
  "Lemon Wave",
  "Bitrate Buzz Funky Funky Kush",
  "Sticky Storm",
  "Turbo Drop",
  "Electric Snap",
  "Crimson OG",
  "Crispy Molten Haze",
  "Dreamy OG",
  "Blazing Ghost Thunder",
  "Neon Frozen Mist",
  "Fastbreak Dream Frosty Atomic Slap",
  "Golden Wild OG",
  "Electric Wild Fog",
  "Spicy Cherry Cookies",
  "Turbo Dank Haze",
  "Purple Snap",
  "Dank Velvet Pop",
  "Electric Atomic Diesel",
  "OBS Kush Electric Frozen Fuel",
  "Turbo Wild OG",
  "Boom Bap Electric Milk",
  "Cherry Haze",
  "Record Flip Lunar Platinum Mist",
  "Atomic Blazing Thunder",
  "Atomic Cookies",
  "Wild Pop",
  "Molten Frosty Mist",
  "Golden Purple Cake",
  "Spicy Purple Fuel",
  "Lemon Ghost Storm",
  "Lemon Jam",
  "Neon Thunder",
  "Molten Midnight Whip",
  "Smooth Haze",
  "Sticky Slap",
  "Frosty Storm",
  "Bubbly Lime Funky Milk",
  "Court Blaze Velvet Ghost Crush",
  "Lunar Punch",
  "Smooth Buzz",
  "Funky Blazing Diesel",
  "Frozen Cloudy Snap",
  "Chico Mist Velvet Lunar Runtz",
  "Atomic Atomic OG",
  "Hazey Cosmic Slap",
  "Purple Pop",
  "Electric Ghost Berry",
  "Electric Cloudy Fuel",
  "Wavy Snap",
  "Blazing Hazey Jam",
  "Turntable Turbo Purple Whip",
  "Sticky Lunar Crush",
  "Hazey Fog",
  "Golden Dreamy Haze",
  "Golden Wave",
  "Ghost Jam",
  "Platinum Roll",
  "Golden Velvet Whip",
  "Frozen Crimson Kush",
  "Molten Funky Snap",
  "Crispy Cherry Haze",
  "Sticky Blast",
  "Frozen Haze",
  "Crispy Glue",
  "Purple Platinum Kush",
  "Spicy Drop",
  "Smooth Cloudy Muffin",
  "Velvet Wild Fog",
  "Spicy Diesel",
  "Vinyl Melt Frozen Jam",
  "Smooth Purple Berry",
  "Stepback OG Golden Cake",
  "Jordan OG Blazing Haze",
  "Boom Bap Electric Pop",
  "Spicy Cosmic Kush",
  "Topo Chico Golden Crispy Roll",
  "Sneaker Drop Electric Roll",
  "Midnight Diesel",
  "Wild Molten Pop",
  "Midnight Hazey Whip",
  "Turbo Midnight Muffin",
  "Groove Dust Golden Drop",
  "Smoky Mountain Midnight Cherry Crush",
  "Sticky Sticky Glue",
  "Atomic Platinum Kush",
  "Volunteer Lemon Sticky Muffin",
  "Molten Jam",
  "Lunar Lemon Thunder",
  "Cherry Roll",
  "Twitch Haze Spicy Blast",
  "Cherry Snap",
  "Electric Turbo Blast",
  "Lunar Cherry Buzz",
  "Molten Whip",
  "Smooth Jam",
  "Sticky Lunar Haze",
  "Mixtape Neon Glue",
  "Frosty Ghost Runtz",
  "Vinyl Frozen Crimson Mist",
  "Wavy Roll",
  "Dank Platinum Storm",
  "Frosty Cloudy Haze",
  "Midnight Milk",
  "OBS Kush Neon Glue",
  "Crimson Smooth Jam",
  "Cosmic Smooth Thunder",
  "Lemon Wild Mist",
  "Purple Spicy OG",
  "Turbo Slap",
  "Wild Frozen Cake",
  "Cloudy Velvet Berry",
  "Electric Haze",
  "Honky Tonk Dreamy Crush",
  "Crimson Jam",
  "Smooth Snap",
  "Neon Runtz",
  "Dreamy Wild Jam",
  "Groove Dust Ghost Roll",
  "Ghost Atomic Glue",
  "Golden Haze",
  "Funky Platinum Cookies",
  "Cloudy Fuel",
  "Platinum Velvet Slap",
  "Topo Dream Crispy Milk",
  "Velvet Platinum Whip",
  "Platinum Crispy OG",
  "Purple Neon Glue",
  "Court Blaze Sticky Jam",
  "Cherry Drizzle",
  "Hazey Slap",
  "Cosmic Fuel",
  "Velvet Wavy Kush",
  "Buckets Kush Spicy Whip",
  "Turbo Crispy Jam",
  "Mineral Buzz Frosty Muffin",
  "Platinum Sticky Pop",
  "Cherry Frozen Jam",
  "Frosty Crispy Drop",
  "Velvet Wild Runtz",
  "Smooth Crimson Crush",
  "Lunar Drop",
  "Molten Thunder",
  "Volunteer Frozen Wavy Kush",
  "Topo Chico Cloudy Platinum Runtz",
  "Spicy Storm",
  "Crimson Neon Diesel",
  "Funky Atomic Buzz",
  "Frozen Cookies",
  "Turbo Storm",
  "Dreamy Buzz",
  "Lunar Platinum Crush",
  "Frozen Cosmic Mist",
  "Crate Digger Dank Ghost Storm",
  "Ghost Turbo Drop",
  "Streamer Atomic Blast",
  "Frosty Lunar Whip",
  "Wild Slap",
  "Deadstock Sticky Wave",
  "Wavy Smooth Haze",
  "Neon Smooth Muffin",
  "Turbo Sticky Mist",
  "Ball Up Velvet Lemon Mist",
  "Funky Frozen Storm",
  "Funky Velvet Thunder",
  "Jordan OG Funky Cookies",
  "Electric Frozen Wave",
  "Ghost Velvet Pop",
  "Lemon Velvet Drop"
]

export default strains;